apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: servicemesh-driver-disk
  namespace: vms
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Block
